name: ESLint
on: [pull_request]
jobs:
  eslint:
    name: runner / eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - run: npm install
      - uses: reviewdog/action-eslint@v1.16.
        with:
          reporter: github-check
          eslint_flags: 'src/'
